version: 2
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: chore
    directory: /
    groups:
      actions-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly

  - package-ecosystem: npm
    commit-message:
      prefix: chore
    directory: /
    groups:
      deps-minor-and-patch:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
      dev-deps-minor-and-patch:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
