import type { Infer, ObjectType } from 'convex/values';

import * as validators from './validators';

export type FavoriteClipArgs = ObjectType<typeof validators.favoriteClipArgs>;
export type FavoriteClipReturns = Infer<typeof validators.favoriteClipReturns>;
export type FavoriteSpeakerArgs = ObjectType<typeof validators.favoriteSpeakerArgs>;
export type FavoriteSpeakerReturns = Infer<typeof validators.favoriteSpeakerReturns>;
export type FavoriteTalkArgs = ObjectType<typeof validators.favoriteTalkArgs>;
export type FavoriteTalkReturns = Infer<typeof validators.favoriteTalkReturns>;
export type FinishTalkArgs = ObjectType<typeof validators.finishTalkArgs>;
export type FinishTalkReturns = Infer<typeof validators.finishTalkReturns>;
export type IsClipFavoritedArgs = ObjectType<typeof validators.isClipFavoritedArgs>;
export type IsClipFavoritedReturns = Infer<typeof validators.isClipFavoritedReturns>;
export type IsSpeakerFavoritedArgs = ObjectType<typeof validators.isSpeakerFavoritedArgs>;
export type IsSpeakerFavoritedReturns = Infer<typeof validators.isSpeakerFavoritedReturns>;
export type IsTalkFavoritedArgs = ObjectType<typeof validators.isTalkFavoritedArgs>;
export type IsTalkFavoritedReturns = Infer<typeof validators.isTalkFavoritedReturns>;
export type IsTalkFinishedArgs = ObjectType<typeof validators.isTalkFinishedArgs>;
export type IsTalkFinishedReturns = Infer<typeof validators.isTalkFinishedReturns>;
export type ListUserFavoritesArgs = ObjectType<typeof validators.listUserFavoritesArgs>;
export type ListUserFavoritesReturns = Infer<typeof validators.listUserFavoritesReturns>;
export type ListUserFinishedTalksArgs = ObjectType<typeof validators.listUserFinishedTalksArgs>;
export type ListUserFinishedTalksReturns = Infer<typeof validators.listUserFinishedTalksReturns>;
export type UnfavoriteClipArgs = ObjectType<typeof validators.unfavoriteClipArgs>;
export type UnfavoriteClipReturns = Infer<typeof validators.unfavoriteClipReturns>;
export type UnfavoriteSpeakerArgs = ObjectType<typeof validators.unfavoriteSpeakerArgs>;
export type UnfavoriteSpeakerReturns = Infer<typeof validators.unfavoriteSpeakerReturns>;
export type UnfavoriteTalkArgs = ObjectType<typeof validators.unfavoriteTalkArgs>;
export type UnfavoriteTalkReturns = Infer<typeof validators.unfavoriteTalkReturns>;
export type UnfinishTalkArgs = ObjectType<typeof validators.unfinishTalkArgs>;
export type UnfinishTalkReturns = Infer<typeof validators.unfinishTalkReturns>;
export type UpdatePasswordArgs = ObjectType<typeof validators.updatePasswordArgs>;
export type UpdatePasswordReturns = Infer<typeof validators.updatePasswordReturns>;
